import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#000',
    zIndex: 1000,
  },
  swiperContainer: {
    width: '100vw',
    height: '100vh',
    position: 'relative',
  },
  swiperSlide: {
    width: '100vw',
    height: '100vh',
    position: 'relative',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000',
  },
  playerStyle: {
    width: '100%',
    height: '100%',
    backgroundColor: '#000',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  episodeInfoOverlay: {
    position: 'absolute',
    bottom: 100,
    left: 20,
    right: 80,
    zIndex: 10,
  },
  episodeTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 8,
  },
  episodeDescription: {
    color: '#ccc',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 8,
  },
  episodeNumber: {
    color: '#888',
    fontSize: 12,
  },
  controlsOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    pointerEvents: 'box-none',
    zIndex: 20,
  },
  topControls: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
    backgroundImage: 'linear-gradient(180deg, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0) 100%)',
    pointerEvents: 'auto',
  },
  closeButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  rightSideControls: {
    position: 'absolute',
    right: 20,
    top: '50%',
    transform: 'translateY(-50%)',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 16,
    pointerEvents: 'auto',
    zIndex: 25,
  },
  favoriteButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  unmuteButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(255, 27, 141, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    shadowColor: '#FF1B8D',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  unmuteButtonText: {
    fontSize: 24,
    color: '#fff',
  },
  tapToPlayOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 50,
  },
  tapToPlayContent: {
    alignItems: 'center',
  },
  tapToPlayIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(255, 27, 141, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    shadowColor: '#FF1B8D',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  tapToPlayIconText: {
    fontSize: 32,
    color: '#fff',
    marginLeft: 4,
  },
  tapToPlayText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  playlistButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  playlistSidebar: {
    position: 'absolute',
    top: 80,
    right: 100,
    width: 320,
    height: 'calc(100vh - 160px)',
    maxHeight: 600,
    backgroundColor: 'rgba(26, 26, 26, 0.95)',
    borderWidth: 1,
    borderColor: '#333',
    borderRadius: 12,
    zIndex: 30,
  },
  playlistHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  playlistTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  playlistContent: {
    flex: 1,
  },
  playlistItem: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  currentPlaylistItem: {
    backgroundColor: 'rgba(255, 27, 141, 0.1)',
    borderLeftWidth: 3,
    borderLeftColor: '#FF1B8D',
  },
  lockedPlaylistItem: {
    opacity: 0.6,
  },
  playlistItemContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  playlistEpisodeNumber: {
    color: '#FF1B8D',
    fontSize: 16,
    fontWeight: 'bold',
    width: 40,
    textAlign: 'center',
  },
  playlistEpisodeInfo: {
    flex: 1,
    marginLeft: 12,
  },
  playlistEpisodeTitle: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 2,
  },
  currentEpisodeTitle: {
    color: '#FF1B8D',
  },
  lockedEpisodeTitle: {
    color: '#888',
  },
  playlistEpisodeDuration: {
    color: '#888',
    fontSize: 12,
  },
  lockIcon: {
    marginLeft: 8,
  },
  premiumText: {
    color: '#FF1B8D',
    fontSize: 10,
    fontWeight: '600',
    backgroundColor: 'rgba(255, 27, 141, 0.2)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  freeIcon: {
    marginLeft: 8,
  },
  freeText: {
    color: '#00D4AA',
    fontSize: 10,
    fontWeight: '600',
    backgroundColor: 'rgba(0, 212, 170, 0.2)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    color: '#fff',
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContainer: {
    backgroundColor: '#2a2a2a',
    borderRadius: 16,
    width: '100%',
    maxWidth: 400,
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  modalTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  modalContent: {
    padding: 20,
  },
  modalMessage: {
    color: '#ccc',
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
  },
  modalActions: {
    flexDirection: 'row',
    padding: 20,
    gap: 12,
  },
  modalSecondaryButton: {
    flex: 1,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#666',
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
  },
  modalSecondaryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '500',
  },
  modalPrimaryButton: {
    flex: 1,
    backgroundColor: '#FF1B8D',
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
  },
  modalPrimaryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  progressBarContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 60,
    backgroundColor: 'transparent',
    zIndex: 25,
    paddingHorizontal: 20,
    paddingVertical: 20,
    backgroundImage: 'linear-gradient(0deg, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0) 100%)',
  },
  progressBarBackground: {
    height: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    borderRadius: 3,
    cursor: 'pointer',
    position: 'relative',
  },
  progressBarFill: {
    height: 6,
    backgroundColor: '#FF1B8D',
    borderRadius: 3,
    transition: 'width 0.1s ease',
  },
  progressBarThumb: {
    position: 'absolute',
    top: -3,
    width: 12,
    height: 12,
    backgroundColor: '#FF1B8D',
    borderRadius: 6,
    marginLeft: -6,
    boxShadow: '0 2px 4px rgba(0,0,0,0.3)',
    transition: 'left 0.1s ease',
  },
  timeDisplay: {
    marginTop: 8,
    alignItems: 'center',
  },
  timeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '500',
  },
  allEpisodesContainer: {
    position: 'absolute',
    bottom: 80,
    left: 20,
    zIndex: 25,
  },
  allEpisodesButton: {
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  allEpisodesButtonText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
});